In [1]:
import numpy as np
import scipy as sp

In [2]:
a = np.array([[1, 1, 2, 3], [1, 4, 5, 6], [1, 7, 8, 9]])
print(a)

[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]


In [3]:
at = a.transpose()
print(at)

[[1 1 1]
 [1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
amul = np.matmul(a, at)
amulinv = np.linalg.inv(amul)
print('inverse = ')
print(amulinv)
print('inv * amul = ')
print(amulinv * amul)

inverse = 
[[ -2.90004521e+14   5.80009043e+14  -2.90004521e+14]
 [  5.80009043e+14  -1.16001809e+15   5.80009043e+14]
 [ -2.90004521e+14   5.80009043e+14  -2.90004521e+14]]
inv * amul = 
[[ -4.35006782e+15   1.91402984e+16  -1.47902306e+16]
 [  1.91402984e+16  -9.04814107e+16   7.13411123e+16]
 [ -1.47902306e+16   7.13411123e+16  -5.65508817e+16]]


In [5]:
amulpinv = np.linalg.pinv(amul)
print('inverse = ')
print(amulpinv)
print('pinv * amul = ')
print(amulpinv * amul)

inverse = 
[[ 0.46296296  0.12962963 -0.2037037 ]
 [ 0.12962963  0.03703704 -0.05555556]
 [-0.2037037  -0.05555556  0.09259259]]
pinv * amul = 
[[  6.94444444   4.27777778 -10.38888889]
 [  4.27777778   2.88888889  -6.83333333]
 [-10.38888889  -6.83333333  18.05555556]]


In [6]:
X = a # original value
Xt = at
print('X = ')
print(X)
print('Xt = ')
print(Xt)
Y = np.array([[1, 0, 3], [2, 3, 4], [3, 1, 3]])
print('Y = ')
print(Y) # target value

X = 
[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]
Xt = 
[[1 1 1]
 [1 4 7]
 [2 5 8]
 [3 6 9]]
Y = 
[[1 0 3]
 [2 3 4]
 [3 1 3]]


In [7]:
# Find w = (XtX)^-1 Xt Y
prefix = np.matmul(Xt, X)
prefix_inv = np.linalg.pinv(prefix)
w = np.matmul(prefix_inv, np.matmul(Xt, Y))
print(w)

[[  1.11111111e-01   1.66666667e-01   1.11111111e+00]
 [  2.99760217e-15  -1.11111111e-01  -1.11111111e+00]
 [  1.11111111e-01   5.55555556e-02  -1.31665512e-15]
 [  2.22222222e-01   2.22222222e-01   1.11111111e+00]]


In [8]:
np.matmul(X, w)

array([[ 1.        ,  0.83333333,  3.33333333],
       [ 2.        ,  1.33333333,  3.33333333],
       [ 3.        ,  1.83333333,  3.33333333]])